### ISSUE TITLE
oxford/newbridge geocoding issue?

### ISSUE THREAD

**Issue by wu-lee** [SolidarityEconomyAssociation/open-data#46]
Certain initiatives seem to be appearing abroad, in Canada and Ireland. This should be deterministic, but some of these seem to differ between the development deployment on `dev-0`, and the (not quite) production deployment on `prod-0`.

@dtmakm27 thinks this may be a problem with the geocoding?

**Comment by dtmakm27** [comment]
@ColmMassey @wu-lee 
It should be fixed in after rebuilding the data 
@wu-lee  do you mind checking if something crashed on either dev or prod from the rebuilds? 

if not could you merge in these changes with yours to master (all work is currently on dev)  and let's update prod

**Comment by ColmMassey** [comment]
Both dev.oxford * dev.newbridge maps still not using OS Postcode data

**Comment by wu-lee** [comment]
I think this issue is related, referencing it here https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/232

**Comment by wu-lee** [comment]
@dtmakm27 - oxford and newbridge both seem to be building on dev-0 and prod-0 without errors. They're building this commit: 

    0b1fc63 added manual lat lon handling for ica

Timestamps look current on the deployed data here:

https://dev.data.solidarityeconomy.coop/sea-lod/oxford/meta.json
```
{
  "timestamp": "2020-09-10 15:00:29 UTC",
  "commit_id": "0b1fc63d12519feed81963c509c2ee8164543190-modified",
  "standard_data_hash": "a1294bbb99d1001bcea4b25e49e40240aec1384a",
  "doc_hash": "fd0b6b5942b755300bf928bd643c9fad6d688f4d",
  "user": "seopendata",
  "host": "dev-0.solidarityeconomy.coop"
}
```
And https://dev.data.solidarityeconomy.coop/sea-lod/newbridge/meta.json
```
{
  "timestamp": "2020-09-10 15:00:48 UTC",
  "commit_id": "0b1fc63d12519feed81963c509c2ee8164543190-modified",
  "standard_data_hash": "949b8ee094191537e323f47f1964221565667a6c",
  "doc_hash": "57eda9fbac91c9ea87357a0ebb775666cd4e7099",
  "user": "seopendata",
  "host": "dev-0.solidarityeconomy.coop"
}
```

**Comment by dtmakm27** [comment]
@ColmMassey 
We didn't clear the previous cache, data was built correctly, but it was using the old data. It's fixed now

**Comment by wu-lee** [comment]
Re: merging - I think none is needed because your changes are on `dev`, and this is what dev-0 and prod-0 currently track.  

We are only looking at dev-0 here, I think? sea-0 uses the old geocoder, as it's on the `master` branch and that hasn't yet been updated to included all the `lod.coop` stuff.

Regarding the `locCache` - I went through all the sea-map websites' `package.json` deploy scripts, and made sure they were 
 - consistent 
 - rsyncing as `www-data:www-data` (the apache user/group) and not `ubuntu:lxd` (an arbitrary consequence of a mistaken `rsync` parameter intended to set the user/group)
 - using the `--delete` option (so that files on the remote server not in the version being deployed are removed)

That last point means that the `locCache` directory gets removed as a matter of course when deploying these sea-map websites using `npm run deploy`
